### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by 1ikeadragon** [thanhquangtran/collaborative-editor#1]
Hi, hope you're doing well. I am also working on a similar project for my college final year. I have some doubts as to how you designed your system and implemented it. Do you have a social or maybe the full documentation for this project? It would be very greatful. Thanks!

**Comment by thanhquangtran** [comment]
Sure! Please send me your email address. I would prefer to exchange through email.

**Comment by debxrshi** [comment]
Hi, please reach me @ dasdebarshi19@gmail.com
